/**
 * workspace-docs store.
 *
 * The canonical store is one SQLite database at
 * `<workspace>/.pi/workspace-docs/store.sqlite`, opened through the built-in
 * `node:sqlite` module. A mutation is one transaction; a stale revision is
 * rejected with no write. The store never resets or rewrites an unreadable
 * database.
 *
 * Each document row keeps its metadata and its canonical body. Checkout renders
 * fresh front matter over that body, so an unchanged round-trip compares equal.
 */
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, statSync } from "node:fs";
import { isAbsolute, join, relative, resolve } from "node:path";
import { DatabaseSync } from "node:sqlite";
import { parseCandidate, renderCandidate, renderFrontMatter, renderGeneratedRegion } from "./grammar.ts";
import { EXPORT_PATH, renderExport } from "./export.ts";
import type { ExportDocument } from "./export.ts";
import {
  nonConformingMetadataDiagnostics,
  resolveDocumentMetadata,
  type DocumentMetadata,
} from "./metadata.ts";
import { publishCompiled } from "./publish.ts";
import type { PublishTarget } from "./publish.ts";
import { renderBody } from "./render.ts";
import { normalizeTermName, renderGlossary } from "./terms.ts";
import type {
  Checkout,
  CompileResult,
  Diagnostic,
  DiscoveryOptions,
  DiscoveryResult,
  DocumentInput,
  DocumentMeta,
  ImportResult,
  IncomingReference,
  ParsedCandidate,
  PreviewResult,
  PreviewSummary,
  PublishOptions,
  PublishResult,
  Section,
  Snapshot,
  TermMatch,
} from "./model.ts";

export const SCHEMA_VERSION = 1;
const DEFAULT_OUTPUT_DIR = ".pi/workspace-docs/out";
const INDEX_DIR = ".pi/workspace-docs";
const INDEX_FILE = `${INDEX_DIR}/index.md`;
const STATE_FILE = `${INDEX_DIR}/publication.json`;
// Workspace-docs owns these paths. A document output-path must never target
// them, or compilation and publication would collide with system artifacts
// (D-3, REQ-COMP-5). The JSON export is reserved by REQ-EXPORT-2.
const RESERVED_PATHS = new Set<string>([
  EXPORT_PATH,
  INDEX_FILE,
  INDEX_DIR,
  `${INDEX_DIR}/out`,
  `${INDEX_DIR}/checkout`,
  `${INDEX_DIR}/store.sqlite`,
  `${INDEX_DIR}/store.sqlite-wal`,
  `${INDEX_DIR}/store.sqlite-shm`,
  STATE_FILE,
]);
const RESERVED_PREFIXES = [`${INDEX_DIR}/checkout/`];
const DISCOVERY_DEFAULT_LIMIT = 50;
const DISCOVERY_MAX_LIMIT = 200;

interface DocumentRow {
  id: string;
  revision: number;
  title: string;
  type: string;
  status: string | null;
  output_path: string | null;
  body: string;
}

export interface Workspace {
  close(): void;
  read(): Snapshot;
  exportSnapshot(): string;
  createDocument(input: DocumentInput): ImportResult;
  checkout(documentId: string): Checkout;
  previewImport(text: string): PreviewResult;
  importCandidate(text: string, token: string): ImportResult;
  compile(): CompileResult;
  publish(options?: PublishOptions): PublishResult;
  discover(options?: DiscoveryOptions): DiscoveryResult;
  incomingReferences(target: string): IncomingReference[];
  hasTarget(target: string): boolean;
  validate(): Diagnostic[];
  lookupTerm(query: string): TermMatch[];
}

function hash(text: string): string {
  return createHash("sha256").update(text).digest("hex");
}

function hasBlock(diagnostics: Diagnostic[]): boolean {
  return diagnostics.some((diagnostic) => diagnostic.severity === "block");
}

/** A Markdown contents list derived from the section hierarchy, in order. */
function renderToc(sections: Section[]): string {
  if (sections.length === 0) return "";
  const minDepth = Math.min(...sections.map((section) => section.depth));
  const lines = ["## Contents", ""];
  for (const section of sections) {
    const indent = "  ".repeat(Math.max(0, section.depth - minDepth));
    lines.push(`${indent}- [${section.heading}](#${section.id})`);
  }
  return lines.join("\n");
}

/** One row per document, with a link from the index to each output. */
function renderIndex(rows: DocumentRow[], paths: Map<string, string>): string {
  const lines = [
    "<!-- generated by workspace-docs. do not edit; compile to regenerate. -->",
    "",
    "# Workspace index",
    "",
    "| ID | Title | Type | Status | Output |",
    "|---|---|---|---|---|",
  ];
  for (const row of rows) {
    const path = paths.get(row.id) as string;
    const link = relative(INDEX_DIR, path).replaceAll("\\", "/");
    lines.push(`| \`${row.id}\` | [${row.title}](${link}) | ${row.type} | ${row.status ?? ""} | \`${path}\` |`);
  }
  lines.push("");
  return lines.join("\n");
}

/**
 * The generated views of one document: its contents and the glossary of its
 * own terms plus every shared term it references. Deterministic for a fixed
 * document and term set, so checkout and import regenerate identical bytes.
 */
function generatedViews(
  parsed: ParsedCandidate,
  documentId: string,
  allTerms: TermMatch[],
): { toc: string; glossary: string } {
  const toc = renderToc(parsed.sections);
  const entries: TermMatch[] = [];
  for (const link of parsed.links) {
    if (!link.to.startsWith("term:")) continue;
    const termId = link.to.slice("term:".length);
    const match = allTerms.find(
      (candidate) => candidate.id === termId && candidate.scope === "shared" && candidate.documentId !== documentId,
    );
    if (match && !entries.some((entry) => entry.id === match.id)) entries.push(match);
  }
  return { toc, glossary: renderGlossary(entries) };
}

/** The D-2 metadata a candidate carries. */
function candidateDocument(candidate: ParsedCandidate): DocumentMetadata {
  return {
    id: candidate.document.id,
    title: candidate.document.title,
    type: candidate.document.type,
    status: candidate.document.status,
    outputPath: candidate.document.outputPath,
  };
}

/** The D-2 metadata a stored row carries. */
function storedDocument(row: DocumentRow): DocumentMetadata {
  return {
    id: row.id,
    title: row.title,
    type: row.type,
    status: row.status ?? undefined,
    outputPath: row.output_path ?? undefined,
  };
}

function omissions(stored: ParsedCandidate, candidate: ParsedCandidate): Diagnostic[] {
  const diagnostics: Diagnostic[] = [];
  const deleted = new Set(candidate.deletions.map((deletion) => deletion.id));
  const records = new Set(candidate.records.map((record) => record.id));
  const terms = new Set(candidate.terms.map((term) => term.id));
  for (const record of stored.records) {
    if (!records.has(record.id) && !deleted.has(record.id)) {
      diagnostics.push({
        severity: "block",
        code: "omission",
        message: `omitted record ${record.id}; remove it with an explicit docs-delete`,
        entity: record.id,
      });
    }
  }
  for (const term of stored.terms) {
    if (!terms.has(term.id) && !deleted.has(term.id)) {
      diagnostics.push({
        severity: "block",
        code: "omission",
        message: `omitted term ${term.id}; remove it with an explicit docs-delete`,
        entity: term.id,
      });
    }
  }
  return diagnostics;
}

const PREVIEW_DIFF_MAX_BYTES = 2048;
const PREVIEW_DIFF_MAX_ITEMS = 200;

/** Truncate UTF-8 text to a byte budget without splitting a character (REQ-TOOL-12). */
function truncateUtf8(text: string, maxBytes: number): { text: string; truncated: boolean } {
  const buffer = Buffer.from(text, "utf8");
  if (buffer.length <= maxBytes) return { text, truncated: false };
  let end = maxBytes;
  while (end > 0 && (buffer[end] & 0xc0) === 0x80) end -= 1;
  return { text: buffer.subarray(0, end).toString("utf8"), truncated: true };
}

/**
 * A structural, non-blocking summary of what an import would change (REQ-MD-3).
 * Identified entities are labelled `<kind>:<id>`. A link has no identity of
 * its own, so it is labelled `<link-type>:<from>-><to>`, which distinguishes
 * links that share endpoints but differ in type. Modified entities also carry
 * a bounded before/after serialization (REQ-TOOL-12).
 */
function summarizeChanges(
  stored: ParsedCandidate,
  candidate: ParsedCandidate,
  resolvedDocument: DocumentMetadata,
): PreviewSummary {
  const summary: PreviewSummary = { added: [], modified: [], omitted: [], unresolved: [], diffs: [] };
  const compare = <T>(
    kind: string,
    previous: Map<string, T>,
    next: Map<string, T>,
    same: (left: T, right: T) => boolean,
    render: (value: T) => string,
  ): void => {
    for (const [id, value] of next) {
      const before = previous.get(id);
      if (before === undefined) {
        summary.added.push(`${kind}:${id}`);
      } else if (!same(before, value)) {
        const label = `${kind}:${id}`;
        summary.modified.push(label);
        if (summary.diffs.length < PREVIEW_DIFF_MAX_ITEMS) {
          const beforeText = truncateUtf8(render(before), PREVIEW_DIFF_MAX_BYTES);
          const afterText = truncateUtf8(render(value), PREVIEW_DIFF_MAX_BYTES);
          summary.diffs.push({
            entity: label,
            before: beforeText.text,
            after: afterText.text,
            truncated: beforeText.truncated || afterText.truncated,
          });
        }
      }
    }
    for (const id of previous.keys()) {
      if (!next.has(id)) summary.omitted.push(`${kind}:${id}`);
    }
  };

  compare(
    "section",
    new Map(stored.sections.map((section) => [section.id, section])),
    new Map(candidate.sections.map((section) => [section.id, section])),
    (left, right) => left.heading === right.heading && left.depth === right.depth && left.body === right.body,
    (section) => JSON.stringify({ heading: section.heading, depth: section.depth, body: section.body }, null, 2),
  );
  compare(
    "record",
    new Map(stored.records.map((record) => [record.id, record])),
    new Map(candidate.records.map((record) => [record.id, record])),
    (left, right) =>
      left.type === right.type &&
      left.status === right.status &&
      left.title === right.title &&
      left.approval === right.approval &&
      left.approvedUsers.join("\u0000") === right.approvedUsers.join("\u0000") &&
      left.approvedAgents.join("\u0000") === right.approvedAgents.join("\u0000") &&
      left.authorization === right.authorization &&
      left.authorizedUsers.join("\u0000") === right.authorizedUsers.join("\u0000") &&
      left.authorizedAgents.join("\u0000") === right.authorizedAgents.join("\u0000") &&
      left.body === right.body,
    (record) =>
      JSON.stringify(
        {
          type: record.type,
          status: record.status,
          title: record.title,
          approval: record.approval,
          approvedUsers: record.approvedUsers,
          approvedAgents: record.approvedAgents,
          authorization: record.authorization,
          authorizedUsers: record.authorizedUsers,
          authorizedAgents: record.authorizedAgents,
          body: record.body,
        },
        null,
        2,
      ),
  );
  compare(
    "term",
    new Map(stored.terms.map((term) => [term.id, term])),
    new Map(candidate.terms.map((term) => [term.id, term])),
    (left, right) =>
      left.name === right.name &&
      left.scope === right.scope &&
      left.body === right.body &&
      left.aliases.join("\u0000") === right.aliases.join("\u0000"),
    (term) => JSON.stringify({ name: term.name, scope: term.scope, aliases: term.aliases, body: term.body }, null, 2),
  );
  // A link has no identity of its own, so its type is part of the key. Two
  // links with the same endpoints but different types are distinct entities.
  const linkKey = (link: { from: string; to: string; type: string }): string =>
    `${link.type}:${link.from}->${link.to}`;
  compare(
    "link",
    new Map(stored.links.map((link) => [linkKey(link), link])),
    new Map(candidate.links.map((link) => [linkKey(link), link])),
    (left, right) => left.type === right.type && left.body === right.body,
    (link) => JSON.stringify({ from: link.from, to: link.to, type: link.type, body: link.body }, null, 2),
  );

  const renderDocument = (document: { title: string; type: string; status?: string; outputPath?: string }): string =>
    JSON.stringify(
      { title: document.title, type: document.type, status: document.status, outputPath: document.outputPath },
      null,
      2,
    );
  const metadata = (document: { title: string; type: string; status?: string; outputPath?: string }): string =>
    `${document.title}\u0000${document.type}\u0000${document.status ?? ""}\u0000${document.outputPath ?? ""}`;
  if (metadata(stored.document) !== metadata(resolvedDocument)) {
    const label = `document:${candidate.document.id}`;
    summary.modified.push(label);
    if (summary.diffs.length < PREVIEW_DIFF_MAX_ITEMS) {
      const beforeText = truncateUtf8(renderDocument(stored.document), PREVIEW_DIFF_MAX_BYTES);
      const afterText = truncateUtf8(renderDocument(resolvedDocument), PREVIEW_DIFF_MAX_BYTES);
      summary.diffs.push({
        entity: label,
        before: beforeText.text,
        after: afterText.text,
        truncated: beforeText.truncated || afterText.truncated,
      });
    }
  }
  return summary;
}

export function openWorkspace(rootDir: string): Workspace {
  const storeDir = join(rootDir, ".pi", "workspace-docs");
  const storePath = join(storeDir, "store.sqlite");
  mkdirSync(storeDir, { recursive: true });

  // A file that already existed is never re-initialized, reset, or migrated
  // (D-1, REQ-STORE-3/4). Only a genuinely absent or empty store is created.
  const existedBefore = existsSync(storePath) && statSync(storePath).size > 0;

  let db: DatabaseSync;
  try {
    db = new DatabaseSync(storePath);
  } catch (error) {
    throw new Error(
      `invalid store: ${storePath} is not a readable workspace-docs database (${(error as Error).message})`,
    );
  }
  try {
    db.prepare("PRAGMA schema_version").get();
  } catch (error) {
    db.close();
    throw new Error(
      `invalid store: ${storePath} is not a readable workspace-docs database (${(error as Error).message})`,
    );
  }

  // Inspect with read-only queries before any write, so a rejected store is
  // left byte-for-byte unchanged.
  const hasMeta = db
    .prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'meta'")
    .get() as { name: string } | undefined;
  const schema = hasMeta
    ? (db.prepare("SELECT value FROM meta WHERE key = 'schema_version'").get() as { value: string } | undefined)
    : undefined;
  const revision = hasMeta
    ? (db.prepare("SELECT value FROM meta WHERE key = 'store_revision'").get() as { value: string } | undefined)
    : undefined;

  const rejectStore = (reason: string): never => {
    db.close();
    throw new Error(`invalid store: ${storePath} ${reason}`);
  };
  if (existedBefore && !hasMeta) rejectStore("has no schema metadata");
  if (schema && schema.value !== String(SCHEMA_VERSION)) {
    rejectStore(`has unsupported schema version ${schema.value}`);
  }
  if (existedBefore && hasMeta && !schema) rejectStore("is missing schema metadata");
  if (schema && !revision) rejectStore("is missing revision metadata");

  db.prepare("PRAGMA journal_mode = WAL").get();
  db.exec("CREATE TABLE IF NOT EXISTS meta (key TEXT PRIMARY KEY, value TEXT NOT NULL)");
  if (!schema) {
    db.prepare("INSERT INTO meta (key, value) VALUES ('schema_version', ?)").run(String(SCHEMA_VERSION));
    db.prepare("INSERT INTO meta (key, value) VALUES ('store_revision', '0')").run();
  }
  db.exec(`CREATE TABLE IF NOT EXISTS documents (
    id TEXT PRIMARY KEY,
    revision INTEGER NOT NULL,
    title TEXT NOT NULL,
    type TEXT NOT NULL,
    status TEXT,
    output_path TEXT,
    body TEXT NOT NULL
  )`);

  const storeRevision = (): number => {
    const row = db.prepare("SELECT value FROM meta WHERE key = 'store_revision'").get() as
      | { value: string }
      | undefined;
    return row ? Number(row.value) : 0;
  };

  const documentRow = (id: string): DocumentRow | undefined =>
    db
      .prepare("SELECT id, revision, title, type, status, output_path, body FROM documents WHERE id = ?")
      .get(id) as DocumentRow | undefined;

  const renderDocument = (row: DocumentRow): string =>
    renderCandidate(
      {
        id: row.id,
        title: row.title,
        type: row.type,
        status: row.status ?? undefined,
        outputPath: row.output_path ?? undefined,
        revision: row.revision,
        storeRevision: storeRevision(),
      },
      row.body,
    );

  const parseStored = (row: DocumentRow): ParsedCandidate => parseCandidate(renderDocument(row));

  const documentRows = (): DocumentRow[] =>
    db
      .prepare("SELECT id, revision, title, type, status, output_path, body FROM documents ORDER BY id")
      .all() as unknown as DocumentRow[];

  const allDocuments = (): { id: string; parsed: ParsedCandidate }[] =>
    documentRows().map((row) => ({ id: row.id, parsed: parseStored(row) }));

  /** One document's complete canonical content for the D-16 JSON export. */
  const exportDocuments = (rows: DocumentRow[]): ExportDocument[] =>
    rows.map((row) => {
      const parsed = parseStored(row);
      return {
        id: row.id,
        title: row.title,
        type: row.type,
        status: row.status ?? undefined,
        outputPath: row.output_path ?? undefined,
        revision: row.revision,
        sections: parsed.sections,
        records: parsed.records,
        terms: parsed.terms,
        links: parsed.links,
      };
    });

  /** Qualify a local `#id` reference with its owning document id. */
  const qualify = (reference: string, documentId: string): string =>
    reference.startsWith("#") ? `${documentId}${reference}` : reference;

  const knownTargets = (documents: { id: string; parsed: ParsedCandidate }[]): Set<string> => {
    const known = new Set<string>();
    for (const { id, parsed } of documents) {
      known.add(id);
      for (const section of parsed.sections) known.add(`${id}#${section.id}`);
      for (const record of parsed.records) known.add(`${id}#${record.id}`);
      for (const term of parsed.terms) known.add(`term:${term.id}`);
    }
    return known;
  };

  /** Unresolved targets introduced by a candidate, for the preview summary (REQ-MD-3). */
  const candidateUnresolved = (candidate: ParsedCandidate): string[] => {
    const known = knownTargets(allDocuments());
    known.add(candidate.document.id);
    for (const section of candidate.sections) known.add(`${candidate.document.id}#${section.id}`);
    for (const record of candidate.records) known.add(`${candidate.document.id}#${record.id}`);
    for (const term of candidate.terms) known.add(`term:${term.id}`);
    const unresolved: string[] = [];
    for (const link of candidate.links) {
      const target = qualify(link.to, candidate.document.id);
      if (!known.has(target)) unresolved.push(target);
    }
    return unresolved;
  };

  /** A deletion is blocked while any document, including the candidate's own, still references the target. */
  const referencedDeletions = (candidate: ParsedCandidate): Diagnostic[] => {
    const documents = allDocuments();
    const self = documents.find(({ id }) => id === candidate.document.id);
    const others = documents.filter(({ id }) => id !== candidate.document.id);
    const diagnostics: Diagnostic[] = [];
    for (const deletion of candidate.deletions) {
      const isTerm = self?.parsed.terms.some((term) => term.id === deletion.id) ?? false;
      const target = isTerm ? `term:${deletion.id}` : `${candidate.document.id}#${deletion.id}`;
      const referrers = new Set<string>();
      for (const { id, parsed } of others) {
        for (const link of parsed.links) {
          if (qualify(link.to, id) === target) referrers.add(qualify(link.from, id));
        }
      }
      for (const link of candidate.links) {
        if (qualify(link.to, candidate.document.id) === target) {
          referrers.add(qualify(link.from, candidate.document.id));
        }
      }
      if (referrers.size > 0) {
        diagnostics.push({
          severity: "block",
          code: "referenced",
          message: `cannot delete ${target}; referenced by ${[...referrers].join(", ")}`,
          entity: target,
        });
      }
    }
    return diagnostics;
  };

  /**
   * True when a path is canonical, workspace-relative, and stays inside the
   * workspace on every platform. Reject `\` explicitly: on Windows it is a
   * separator, but `split("/")` would not see it as an escaping segment.
   */
  const isCanonicalOutputPath = (outputPath: string): boolean => {
    if (
      outputPath.length === 0 ||
      outputPath.includes("\\") ||
      outputPath.startsWith("/") ||
      isAbsolute(outputPath) ||
      outputPath.split("/").some((segment) => segment === "" || segment === "." || segment === "..")
    ) {
      return false;
    }
    const rel = relative(rootDir, resolve(rootDir, outputPath)).replaceAll("\\", "/");
    return rel.length > 0 && rel !== ".." && !rel.startsWith("../");
  };

  /** Enforce D-3 path containment and uniqueness for one document. */
  const outputPathDiagnostics = (id: string, outputPath: string | undefined): Diagnostic[] => {
    if (!id || outputPath === undefined) return [];
    if (!isCanonicalOutputPath(outputPath)) {
      return [
        {
          severity: "block",
          code: "output-path",
          message: `output-path must be a canonical workspace-relative path with no empty, "." or ".." segment: ${outputPath}`,
        },
      ];
    }
    if (RESERVED_PATHS.has(outputPath) || RESERVED_PREFIXES.some((prefix) => outputPath.startsWith(prefix))) {
      return [
        {
          severity: "block",
          code: "output-path-collision",
          message: `output-path is reserved by workspace-docs: ${outputPath}`,
        },
      ];
    }
    for (const row of documentRows()) {
      if (row.id === id) continue;
      const otherPath = row.output_path ?? `${DEFAULT_OUTPUT_DIR}/${row.id}.md`;
      if (otherPath === outputPath) {
        return [
          {
            severity: "block",
            code: "output-path-collision",
            message: `output-path is already used by ${row.id}: ${outputPath}`,
          },
        ];
      }
    }
    return [];
  };

  /** Every term definition in the store, with its scope and owning document. */
  const termMatches = (): TermMatch[] =>
    allDocuments().flatMap(({ id, parsed }) =>
      parsed.terms.map((term) => ({
        id: term.id,
        name: term.name,
        aliases: term.aliases,
        scope: term.scope,
        documentId: id,
        body: term.body,
      })),
    );

  /** Enforce D-7 term identity and normalized name/alias uniqueness. */
  const termDiagnostics = (candidate: ParsedCandidate): Diagnostic[] => {
    const diagnostics: Diagnostic[] = [];
    const existing = termMatches().filter((match) => match.documentId !== candidate.document.id);
    const existingShared = existing.filter((match) => match.scope === "shared");
    const existingNames = new Map<string, string>();
    for (const match of existingShared) {
      existingNames.set(normalizeTermName(match.name), match.id);
      for (const alias of match.aliases) existingNames.set(normalizeTermName(alias), match.id);
    }
    const sharedNames = new Map<string, string>();
    const localNames = new Map<string, string>();
    for (const term of candidate.terms) {
      if (term.scope !== "shared") {
        const key = normalizeTermName(term.name);
        const duplicate = localNames.get(key);
        if (duplicate) {
          diagnostics.push({
            severity: "block",
            code: "term-name",
            message: `local term name "${key}" is used by both ${duplicate} and ${term.id}`,
            entity: term.id,
          });
        }
        localNames.set(key, term.id);
        continue;
      }
      const owner = existingShared.find((match) => match.id === term.id);
      if (owner) {
        diagnostics.push({
          severity: "block",
          code: "term-id",
          message: `shared term ${term.id} is already defined in ${owner.documentId}`,
          entity: term.id,
        });
      }
      for (const key of [normalizeTermName(term.name), ...term.aliases.map(normalizeTermName)]) {
        const other = existingNames.get(key);
        if (other && other !== term.id) {
          diagnostics.push({
            severity: "block",
            code: "term-name",
            message: `term name or alias "${key}" is already used by shared term ${other}`,
            entity: term.id,
          });
        }
        const duplicate = sharedNames.get(key);
        if (duplicate && duplicate !== term.id) {
          diagnostics.push({
            severity: "block",
            code: "term-name",
            message: `term name or alias "${key}" is used by both ${duplicate} and ${term.id}`,
            entity: term.id,
          });
        }
        sharedNames.set(key, term.id);
      }
    }
    return diagnostics;
  };

  const reject = (code: string, message: string): ImportResult => ({
    status: "rejected",
    storeRevision: storeRevision(),
    diagnostics: [{ severity: "block", code, message }],
  });

  /**
   * Enforce REQ-MD-8: a generated region a candidate carries must equal the
   * view regenerated from the store, so an edit inside one cannot change the
   * store or silently alter a shared definition. A missing region is allowed.
   */
  const generatedRegionDiagnostics = (candidate: ParsedCandidate, stored: ParsedCandidate): Diagnostic[] => {
    const expected = generatedViews(stored, stored.document.id, termMatches());
    const diagnostics: Diagnostic[] = [];
    for (const region of candidate.generated) {
      const want = region.name === "toc" ? expected.toc : region.name === "glossary" ? expected.glossary : undefined;
      if (want === undefined || region.content === want) continue;
      diagnostics.push({
        severity: "block",
        code: "generated-region",
        message: `generated ${region.name} region does not match the store; regenerate it with \`workspace-docs checkout\``,
        line: region.line,
      });
    }
    return diagnostics;
  };

  const bumpStoreRevision = (): number => {
    const next = storeRevision() + 1;
    db.prepare("UPDATE meta SET value = ? WHERE key = 'store_revision'").run(String(next));
    return next;
  };

  const transact = <T>(fn: () => T): T => {
    db.exec("BEGIN IMMEDIATE");
    try {
      const result = fn();
      db.exec("COMMIT");
      return result;
    } catch (error) {
      db.exec("ROLLBACK");
      throw error;
    }
  };

  const buildCompile = (): CompileResult => {
    const rows = documentRows();
    const paths = new Map(rows.map((row) => [row.id, row.output_path ?? `${DEFAULT_OUTPUT_DIR}/${row.id}.md`]));
    const allTerms = termMatches();
    const files = rows.map((row) => {
      const path = paths.get(row.id) as string;
      const header = `<!-- generated by workspace-docs. source: ${row.id} revision ${row.revision}. do not edit; author with workspace-docs checkout. -->`;
      const parsed = parseStored(row);
      const { toc, glossary } = generatedViews(parsed, row.id, allTerms);
      const body = renderBody(parsed.rawBody, path, (documentId) => paths.get(documentId));
      const content = `${header}\n\n# ${row.title}\n${toc ? `\n${toc}\n` : ""}${glossary ? `\n${glossary}\n` : ""}${body ? `\n${body}\n` : ""}`;
      return { path, content };
    });
    files.push({ path: INDEX_FILE, content: renderIndex(rows, paths) });
    files.push({ path: EXPORT_PATH, content: renderExport(storeRevision(), exportDocuments(rows)) });
    files.sort((left, right) => (left.path < right.path ? -1 : left.path > right.path ? 1 : 0));
    const seenPaths = new Set<string>();
    for (const file of files) {
      if (seenPaths.has(file.path)) throw new Error(`duplicate compiled output path: ${file.path}`);
      seenPaths.add(file.path);
    }
    return { storeRevision: storeRevision(), files };
  };

  return {
    close() {
      db.close();
    },

    read(): Snapshot {
      const rows = db
        .prepare("SELECT id, revision, title, type, status, output_path, body FROM documents ORDER BY id")
        .all() as unknown as DocumentRow[];
      const documents: DocumentMeta[] = rows.map((row) => ({
        id: row.id,
        title: row.title,
        type: row.type,
        status: row.status ?? undefined,
        outputPath: row.output_path ?? undefined,
        revision: row.revision,
      }));
      return { storeRevision: storeRevision(), documents };
    },

    exportSnapshot(): string {
      return renderExport(storeRevision(), exportDocuments(documentRows()));
    },

    createDocument(input: DocumentInput): ImportResult {
      const resolution = resolveDocumentMetadata({
        id: input.id,
        title: input.title,
        type: input.type,
        status: input.status,
        outputPath: input.outputPath,
      });
      if (hasBlock(resolution.diagnostics)) {
        return { status: "rejected", storeRevision: storeRevision(), diagnostics: resolution.diagnostics };
      }
      const metadata = resolution.metadata;
      if (documentRow(metadata.id)) return reject("document-exists", `document already exists: ${metadata.id}`);
      const pathIssue = outputPathDiagnostics(metadata.id, metadata.outputPath);
      if (pathIssue.length > 0) {
        return { status: "rejected", storeRevision: storeRevision(), diagnostics: pathIssue };
      }
      return transact(() => {
        if (documentRow(metadata.id)) return reject("document-exists", `document already exists: ${metadata.id}`);
        db.prepare(
          "INSERT INTO documents (id, revision, title, type, status, output_path, body) VALUES (?, ?, ?, ?, ?, ?, ?)",
        ).run(
          metadata.id,
          1,
          metadata.title,
          metadata.type,
          metadata.status ?? null,
          metadata.outputPath ?? null,
          "",
        );
        return { status: "committed", storeRevision: bumpStoreRevision(), documentRevision: 1, diagnostics: [] };
      });
    },

    checkout(documentId: string): Checkout {
      const row = documentRow(documentId);
      if (!row) throw new Error(`unknown document: ${documentId}`);
      const parsed = parseStored(row);
      const { toc, glossary } = generatedViews(parsed, row.id, termMatches());
      let text = renderFrontMatter({
        id: row.id,
        title: row.title,
        type: row.type,
        status: row.status ?? undefined,
        outputPath: row.output_path ?? undefined,
        revision: row.revision,
        storeRevision: storeRevision(),
      });
      if (toc) text += renderGeneratedRegion("toc", toc);
      text += parsed.rawBody;
      if (glossary) {
        if (!text.endsWith("\n")) text += "\n";
        text += renderGeneratedRegion("glossary", glossary);
      }
      return {
        documentId,
        text,
        baseRevision: row.revision,
        baseStoreRevision: storeRevision(),
      };
    },

    previewImport(text: string): PreviewResult {
      const candidate = parseCandidate(text);
      const diagnostics = [...candidate.diagnostics];
      const summary: PreviewSummary = { added: [], modified: [], omitted: [], unresolved: [], diffs: [] };
      const row = candidate.document.id ? documentRow(candidate.document.id) : undefined;
      if (!hasBlock(diagnostics) && row) {
        const stored = parseStored(row);
        const resolution = resolveDocumentMetadata(candidateDocument(candidate), storedDocument(row));
        diagnostics.push(...resolution.diagnostics);
        diagnostics.push(...omissions(stored, candidate));
        diagnostics.push(...generatedRegionDiagnostics(candidate, stored));
        diagnostics.push(...referencedDeletions(candidate));
        if (resolution.outputPathChanged) {
          diagnostics.push(...outputPathDiagnostics(resolution.metadata.id, resolution.metadata.outputPath));
        }
        diagnostics.push(...termDiagnostics(candidate));
        const changes = summarizeChanges(stored, candidate, resolution.metadata);
        summary.added = changes.added;
        summary.modified = changes.modified;
        summary.omitted = changes.omitted;
        summary.unresolved = candidateUnresolved(candidate);
        summary.diffs = changes.diffs;
      }
      return { token: hash(text), candidateHash: hash(text), diagnostics, summary };
    },

    importCandidate(text: string, token: string): ImportResult {
      if (hash(text) !== token) return reject("candidate-changed", "candidate changed after preview; preview it again");
      const candidate = parseCandidate(text);
      if (hasBlock(candidate.diagnostics)) {
        return { status: "rejected", storeRevision: storeRevision(), diagnostics: candidate.diagnostics };
      }
      const row = documentRow(candidate.document.id);
      if (!row) return reject("document-missing", `unknown document: ${candidate.document.id}; create it first`);
      if (candidate.baseRevision !== row.revision || candidate.baseStoreRevision !== storeRevision()) {
        return reject("revision", `outdated revision for ${candidate.document.id}; check out again`);
      }
      const stored = parseStored(row);
      const resolution = resolveDocumentMetadata(candidateDocument(candidate), storedDocument(row));
      if (hasBlock(resolution.diagnostics)) {
        return { status: "rejected", storeRevision: storeRevision(), diagnostics: resolution.diagnostics };
      }
      const found = omissions(stored, candidate);
      if (found.length > 0) {
        return { status: "rejected", storeRevision: storeRevision(), diagnostics: found };
      }
      const regionIssue = generatedRegionDiagnostics(candidate, stored);
      if (regionIssue.length > 0) {
        return { status: "rejected", storeRevision: storeRevision(), diagnostics: regionIssue };
      }
      const referenced = referencedDeletions(candidate);
      if (referenced.length > 0) {
        return { status: "rejected", storeRevision: storeRevision(), diagnostics: referenced };
      }
      if (resolution.outputPathChanged) {
        const pathIssue = outputPathDiagnostics(resolution.metadata.id, resolution.metadata.outputPath);
        if (pathIssue.length > 0) {
          return { status: "rejected", storeRevision: storeRevision(), diagnostics: pathIssue };
        }
      }
      const termIssue = termDiagnostics(candidate);
      if (termIssue.length > 0) {
        return { status: "rejected", storeRevision: storeRevision(), diagnostics: termIssue };
      }
      const changed =
        stored.rawBody !== candidate.rawBody ||
        row.title !== resolution.metadata.title ||
        row.type !== resolution.metadata.type ||
        (row.status ?? undefined) !== resolution.metadata.status ||
        (row.output_path ?? undefined) !== resolution.metadata.outputPath;
      if (!changed) {
        return { status: "unchanged", storeRevision: storeRevision(), documentRevision: row.revision, diagnostics: [] };
      }
      return transact(() => {
        const fresh = documentRow(candidate.document.id);
        if (!fresh || fresh.revision !== candidate.baseRevision || storeRevision() !== candidate.baseStoreRevision) {
          return reject("revision", `outdated revision for ${candidate.document.id}; check out again`);
        }
        db.prepare(
          "UPDATE documents SET body = ?, title = ?, type = ?, status = ?, output_path = ?, revision = revision + 1 WHERE id = ?",
        ).run(
          candidate.rawBody,
          resolution.metadata.title,
          resolution.metadata.type,
          resolution.metadata.status ?? null,
          resolution.metadata.outputPath ?? null,
          candidate.document.id,
        );
        return {
          status: "committed",
          storeRevision: bumpStoreRevision(),
          documentRevision: fresh.revision + 1,
          diagnostics: [],
        };
      });
    },

    compile: buildCompile,

    publish(options: PublishOptions = {}): PublishResult {
      const compiled = buildCompile();
      const ids = new Map(
        documentRows().map((row) => [row.output_path ?? `${DEFAULT_OUTPUT_DIR}/${row.id}.md`, row.id]),
      );
      const targets: PublishTarget[] = compiled.files.map((file) => ({
        path: file.path,
        absolutePath: join(rootDir, file.path),
        content: file.content,
        documentId: ids.get(file.path) ?? "",
      }));
      const { outcomes, diagnostics } = publishCompiled(rootDir, targets, options);
      return { storeRevision: compiled.storeRevision, outcomes, diagnostics };
    },

    discover(options: DiscoveryOptions = {}): DiscoveryResult {
      const query = options.query?.trim().toLowerCase();
      const matching = documentRows().filter((row) => {
        if (options.type !== undefined && row.type !== options.type) return false;
        if (options.status !== undefined && (row.status ?? undefined) !== options.status) return false;
        if (query && !row.id.toLowerCase().includes(query) && !row.title.toLowerCase().includes(query)) return false;
        return true;
      });
      const offset = Math.max(0, options.offset ?? 0);
      const limit = Math.min(DISCOVERY_MAX_LIMIT, Math.max(0, options.limit ?? DISCOVERY_DEFAULT_LIMIT));
      const entries = matching.slice(offset, offset + limit).map((row) => ({
        id: row.id,
        title: row.title,
        type: row.type,
        status: row.status ?? undefined,
        outputPath: row.output_path ?? undefined,
        revision: row.revision,
      }));
      return { total: matching.length, entries };
    },

    incomingReferences(target: string): IncomingReference[] {
      const references: IncomingReference[] = [];
      for (const { id, parsed } of allDocuments()) {
        for (const link of parsed.links) {
          if (qualify(link.to, id) === target) {
            references.push({ from: qualify(link.from, id), to: qualify(link.to, id), type: link.type });
          }
        }
      }
      return references;
    },

    hasTarget(target: string): boolean {
      return knownTargets(allDocuments()).has(target);
    },

    validate(): Diagnostic[] {
      const documents = allDocuments();
      const known = knownTargets(documents);
      const diagnostics: Diagnostic[] = [];
      for (const { id, parsed } of documents) {
        diagnostics.push(...parsed.diagnostics);
        diagnostics.push(...nonConformingMetadataDiagnostics(parsed.document));
        for (const link of parsed.links) {
          const from = qualify(link.from, id);
          const to = qualify(link.to, id);
          if (!known.has(to)) {
            diagnostics.push({
              severity: "warn",
              code: "unresolved",
              message: `unresolved reference from ${from} to ${to}`,
              entity: to,
            });
          }
          if (!known.has(from)) {
            diagnostics.push({
              severity: "warn",
              code: "unresolved",
              message: `unresolved reference from ${from} to ${to}`,
              entity: from,
            });
          }
          const targetDocumentId = link.to.startsWith("term:")
            ? undefined
            : link.to.startsWith("#")
              ? id
              : link.to.split("#")[0];
          if (
            targetDocumentId !== undefined &&
            documents.find((entry) => entry.id === targetDocumentId)?.parsed.document.status === "retired"
          ) {
            diagnostics.push({
              severity: "warn",
              code: "retired-target",
              message: `link from ${from} targets retired document ${targetDocumentId}`,
              entity: targetDocumentId,
            });
          }
        }
      }
      return diagnostics;
    },

    lookupTerm(query: string): TermMatch[] {
      const needle = normalizeTermName(query);
      return termMatches().filter(
        (match) =>
          normalizeTermName(match.name) === needle ||
          match.aliases.some((alias) => normalizeTermName(alias) === needle),
      );
    },
  };
}
